### ISSUE TITLE
Bookmarking

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#3255]
Add bookmarking (optional with comments) to lines (indicator should be visible in list view + waveform).
Booksmarks are not saved atm, but could perhaps be saved in e.g. first line, config file, or ...

Suggestions/comments are welcome - latest beta contains some functionality/shortcuts for this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

( Was attempted earlier in #1806 )

**Comment by marb99** [comment]
save the bookmarks is essential and see comments added not only on the waveform

**Comment by marb99** [comment]
@niksedk  it is possible hide the tooltip when open SE

![capturar](https://user-images.githubusercontent.com/7856897/50538733-d2598880-0b6b-11e9-9a7e-e31b1e198156.PNG)

**Comment by OmrSi** [comment]
language master minor https://github.com/SubtitleEdit/subtitleedit/blob/cf37883ce39925c39441d646250c9e8c75dac876/LanguageMaster.xml#L1749 "previous".

**Comment by marb99** [comment]
@niksedk I can't compile this build 19 give me an error

"Error	CS0117	'Resources' does not contain a definition for 'bookmark21'	SubtitleEdit"

![capturar](https://user-images.githubusercontent.com/7856897/50539139-e6ed4f00-0b72-11e9-993e-751f7dd617a0.PNG)

**Comment by marb99** [comment]
@niksedk see this gif, the line mark disappear after hit new sub and reopen 

![1](https://user-images.githubusercontent.com/7856897/50539450-64678e00-0b78-11e9-9f42-18cd28dd1bfe.gif)

**Comment by marb99** [comment]
@**niksedk** the Subtitle Workshop saves the bookmarks in a separate file, not in subtitle file.

in the same folder as the open subtitle, I think it's a good idea because of the subtitle compatibility
and to avoid problems with other editors and players.

![capturar](https://user-images.githubusercontent.com/7856897/50539642-7139b100-0b7b-11e9-9c6a-0c76cb66c783.PNG)

**Comment by niksedk** [comment]
Thx for the info :)

Source + beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

The bookmark info is atm saved in first line... this could both be good and bad - good because you can share bookmarks - bad because you might accidentally share bookmarks without wanting to share bookmarks.... ;) 
Perhaps a dismiss-able warning when saving?

**Comment by niksedk** [comment]
What do you mean by `for example the MPC-BE player show the bookmarks as lines in subtitle` ?

**Comment by OmrSi** [comment]
@niksedk This is all amazing, good work. Thanks a lot.

I still have a comment about the appearance, though.
I don't think it looks good with spaces If there is a line with a number higher than 999.
So, maybe add a separator named B and move # to the right?
![screenshot 34](https://user-images.githubusercontent.com/20923700/50539995-46a72280-0b92-11e9-86f3-be77640db84a.png)

**Comment by marb99** [comment]
@niksedk  the context menu for edit and remove bookmark  appears in a very low position and cuts the menu.
And the bookmark in listview line number still not appear after hit the button new and reopen

![1](https://user-images.githubusercontent.com/7856897/50540316-7bfa4300-0b87-11e9-82f5-67df44932b65.gif)

**Comment by marb99** [comment]
@niksedk after compile the built 23 when hit "remove or clear  bookmarks the context menu appears in other place of screen

![1](https://user-images.githubusercontent.com/7856897/50541942-9abd0180-0ba8-11e9-8d73-2cf0757b23d2.gif)

**Comment by niksedk** [comment]
@marb99: thx, hopefully fixed now.

**Comment by marb99** [comment]
@**niksedk** it works now, you've been doing an excellent job and I've been pain in ass, my written English is not the best, but I try to help with what I can by detecting errors and testing.

Happy New Year ;)

**Comment by OmrSi** [comment]
@marb99 Indeed. He's put up with me much, too. Wish he knows how much we appreciate this. :)

Since all above issues have been solved, I thought I'd bring this down here.
@niksedk This is all amazing, good work. Thanks a lot.

- I still have a comment about the appearance, though.
I don't think it looks good with spaces If there is a line with a number higher than 999.
So, maybe add a separator named B or has no name and move # to the right?
![screenshot 34](https://user-images.githubusercontent.com/20923700/50539995-46a72280-0b92-11e9-86f3-be77640db84a.png)
Another thing that supports this suggestion is that if you add then delete a bookmark, the numbers return left:
![screenshot 37](https://user-images.githubusercontent.com/20923700/50540347-da7bed00-0b98-11e9-97cf-79f14e700eaa.png)
![screenshot 38](https://user-images.githubusercontent.com/20923700/50540350-e7004580-0b98-11e9-87dc-7c8081e622dc.png)

- Noticed an issue with the shortcuts while testing:
![screenshot 36](https://user-images.githubusercontent.com/20923700/50540225-9556bb80-0b96-11e9-9603-f2f3d2777ffa.png)
They take the same one.

- Joining two subs makes a problem and 0 is counted as a line and that causes problems with joining, I joined two subs, one with and one without:
![screenshot 39](https://user-images.githubusercontent.com/20923700/50540388-8cb3b480-0b99-11e9-9c07-a744e8099ec9.png)

**Comment by niksedk** [comment]
@marb99 / @OmrSi: It's super nice with your useful comments and testing :)
It always makes SE better.

Happy New Year!

**Comment by darnn** [comment]
Happy new year! And thank you for all the work you do! SE truly makes me happy on a profound level, and I want you to know that it's appreciated.

**Comment by marb99** [comment]
@OmrSi I think it's okay like this, is a temp file, when the work on the subtitle is finished it is deleted and thus it is avoided to have a folder full of temp files.

@**niksedk** I think the name should identify the program so we know it's an SE file...
for example **SE.bookmarks** or something like that

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

Should be pretty ready now :)

**Comment by OmrSi** [comment]
Looks good, but did you intend to make the line number go left if there is no bookmark?
I still think a separate column would be better.
![screenshot 42](https://user-images.githubusercontent.com/20923700/50560979-cb1eb000-0d0e-11e9-95d9-a71c289c54ec.png)

**Comment by OmrSi** [comment]
I have an idea, How about the column size changes depending on whether a bookmark exists in the file or not?

**Comment by niksedk** [comment]
@OmrSi: Yes, that seems easy to do (I hope): https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip


>And this issue is still there #3255 (comment) (in build 34 that is).

Seems fixed :)

**Comment by OmrSi** [comment]
The second one is fixed. :D

About the first, now the default size is 50, which fits like 6 numbers, 999999.
It would be better if it takes the number stored in the settings file, then add the bookmark size to it, I don't know if that would be possible. So, If I had 38 stored in my settings file, or resized the column to a size which is saved in the settings, it would take that number and add the bookmark icon size to it, not go back to the default 50 all the time.

**Comment by niksedk** [comment]
OK, gave it a try - how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip ?

**Comment by OmrSi** [comment]
Perfect. :D
Thanks. <3

**Comment by OmrSi** [comment]
I just noticed that something goes wrong when you open an original subtitle:
![screenshot 49](https://user-images.githubusercontent.com/20923700/50593424-f5a07280-0ea0-11e9-9f41-25e935259e64.png)

**Comment by niksedk** [comment]
@OmrSi: nice catch :)
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Works perfectly. :)
I don't think there is anything else.

**Comment by OmrSi** [comment]
@niksedk This is a minor: 
When opening SE # is:
![screenshot 53](https://user-images.githubusercontent.com/20923700/50651258-7a67bb00-0f8b-11e9-9710-d45a4025b37f.png)

When closing and opening the file:
![screenshot 54](https://user-images.githubusercontent.com/20923700/50651296-910e1200-0f8b-11e9-946f-5465d34990e3.png)

**Comment by OmrSi** [comment]
@niksedk If you open and close SE while RTL mode is activated, ListViewNumberWidth always resets to 20 then 55 when opening again, then 37 then 20 again and so on.
![screenshot 132](https://user-images.githubusercontent.com/20923700/51686522-32234200-1ff9-11e9-9324-ecdf1431f5e2.png)
![screenshot 133](https://user-images.githubusercontent.com/20923700/51686527-33546f00-1ff9-11e9-8c35-e26016004212.png)
![screenshot 134](https://user-images.githubusercontent.com/20923700/51686532-35b6c900-1ff9-11e9-9366-08154c3aa0e8.png)

**Comment by niksedk** [comment]
Bookmarks can also be toggled via the list view context menu:
![image](https://user-images.githubusercontent.com/1261331/52198550-89c87580-2863-11e9-90bc-4040ff6e1cf1.png)

**Comment by kaderr569** [comment]
### Nice
**Helpful post**
<a href='https://nofelmedia.blogspot.com/?m=1'> Nofel Media </a>
