### ISSUE TITLE
VobSub export preserves all settings except bottom margin value

### ISSUE THREAD

**Issue by kachijs** [SubtitleEdit/subtitleedit#3775]
Open VobSub (export) configure - font, font size, resolution etc. Next time i open export window all settings are preserved except Bottom margin = 15 % (before 5%). I then change the value to 5% but again value is back to 15%.
I checked and all versions starting from 3.5.4 do this. 3.5.3 is not affected.

**Comment by niksedk** [comment]
Should be fixed in latest beta I hope: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by kachijs** [comment]
Yes. It stays at 5% every time. But i have another issue regarding subtitle placement. When the subs are exported through GUI they are placed lover on the screen than subs that are exported through command line. Both subs are SRT and exported to VobSub.  Same Settings.xml is used. 

Command line: 
_SubtitleEdit.exe /convert fi.srt VobSub /outputfolder:"C:\Users\XXXX\Desktop\SubtitleEdit_3510\SubtitleEditBeta"_
  
<img width="959" alt="fin" src="https://user-images.githubusercontent.com/861217/65540750-b0334200-df14-11e9-83f2-e622e80ea6bd.PNG">
<img width="960" alt="nor" src="https://user-images.githubusercontent.com/861217/65540751-b0334200-df14-11e9-8290-e122f631f6e5.PNG">

**Comment by niksedk** [comment]
@kachijs: How is latest beta?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by kachijs** [comment]
@niksedk: It's still buggy. When i set bottom margin 15%  and export IDX/SUB through GUi everything is correct also when i set 5% bottom margin placement of subtitles is correct. 
Using command line is different story. When 5% is set placement is bit higher then it is exporting through GUI (5%). When 15% is set placement does not changes. It stays at the same level as before (when using 5% through cmd).

So it looks like bottom margin value is ignored/hardcoded using command line conversion.

With latest beta and bottom margin 15% (export through gui)
<img width="960" alt="latest_gui_15prc" src="https://user-images.githubusercontent.com/861217/66303688-3df33200-e904-11e9-8c3f-d77ed705fa87.PNG">


Latest beta and bottom margin 15% (export through cmd)
<img width="960" alt="latest_cmd_15prc" src="https://user-images.githubusercontent.com/861217/66303701-40ee2280-e904-11e9-96be-6d83906a51e9.PNG">


With latest beta and bottom margin 5% (export through gui)
<img width="960" alt="latest_gui" src="https://user-images.githubusercontent.com/861217/66303709-43e91300-e904-11e9-8aa1-74785603359b.PNG">


Latest beta and bottom margin 5% (export through cmd)
<img width="960" alt="latest_cmd" src="https://user-images.githubusercontent.com/861217/66303713-464b6d00-e904-11e9-8daf-74747cea3100.PNG">

**Comment by niksedk** [comment]
OK, could reproduce the error - hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

**Comment by kachijs** [comment]
@niksedk it seems to work now correctly. Thank you!

**Comment by niksedk** [comment]
@kachijs: thx for reporting and testing :)

**Comment by kachijs** [comment]
@niksedk sorry, but i found another bug regarding placement of VobSub after export. So now exporting subtitles through command line works as expected but doing the same through GUI places subtitles on the left side of the screen.... ignoring left/right margin?

![exporing_gui](https://user-images.githubusercontent.com/861217/66393400-1f139f00-e9db-11e9-934a-727ad6653cf8.PNG)

**Comment by niksedk** [comment]
@kachijs: Could you try latest beta again?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.10/SubtitleEditBeta.zip

I've not really fixed anything, but I'm unable to re-create this UI vobsub issue.
