### ISSUE TITLE
The preview font isn't working when in WebVTT format.

### ISSUE THREAD

**Issue by JustDevs** [SubtitleEdit/subtitleedit#6970]
Subtitle preview is enlarged and doesn't use the font in video player settings when working in WebVTT format. But it works fine when in .srt format.

![nvMC961oDG](https://github.com/SubtitleEdit/subtitleedit/assets/22374647/4d679784-b4f3-4e2e-bae1-28b8609572c2)

You need to open a .vtt file to see it. It looks fine when switching from .srt to .vtt from top bar, but not when directly opening one.

**Comment by GrampaWildWilly** [comment]
I can confirm this.  I was a bit surprised by this, too.  I went hunting in the SE Settings & found something that affects this.  On the Video Player page of the settings dialog, when you have the MPV player selected as your Video Engine, there is a check box for "mpv handles preview text."  If that box is checked, there are several font-related settings that display in the body of the panel.  Your choices there for font & font size seem to be ignored.  If you uncheck that box, the font & font size are still shown as available for you to set.  But a few other settings disappear, settings controlling colors & borders.  When MPV is blocked from handling the preview text, your selections of font & font size on this page of settings look like they are honored.  I'm not entirely sure but to my way of thinking, this tells me that when that box is checked, MPV doesn't permit control of the font.  No, that can't be true.  Surely it's just a matter of using the right API call to pass the font information from SE to MPV.

But there's a second issue.  When MPV is controlling the preview font, the subtitles appear on top of the video in both fullscreen & not fullscreen.  (I run with the video controls undocked.  I keep the editing window on my primary monitor & transfer the MPV window to my secondary monitor, which is my TV.)  But when you stop MPV from controlling the preview font, you lose a part of the video aperture.  The video image is shrunk in order to offer a gray box below the video image within the video player.  This box is the full width of the display, both in fullscreen & not in fullscreen.  The gray box becomes the location of the subtitles.  I repeat, this is true both in fullscreen & not fullscreen.  Seems to me I suggested a while ago that the MPV video image in fullscreen actually occupy the full screen, a change that you (Nik) made.  So it looks like that older fix needs to be ported into this situation.

To illustrate, I'm attaching 2 images of my 2 monitors to this post.  Image #01 shows what it looks like when the box is unchecked for MPV handling preview text.  Image #02 shows the case when the box is checked.

I believe that makes 2 issues to deal with here.

<img width="1920" alt="#01" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/380d9ee4-cc84-4386-a819-666953e50c57">
<img width="1920" alt="#02" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/f12177f2-b046-47c8-b61a-5431d147a8e4">

**Comment by niksedk** [comment]
Please attach some sample files.

In SE 3.6.13 mpv handles the raw VTT file. 
To improve this, SE would probably need to convert styles from VTT to ASSA...

**Comment by JustDevs** [comment]
> 

You mean I should post a VTT file?

**Comment by niksedk** [comment]
Yes, do post a file.

VTT files can contain font names/sizes and styles which should be used in the preview.
ATM, mpv handles the VTT preview stuff, so the "video player settings" is not used.

**Comment by JustDevs** [comment]
> Yes, do post a file.
> 
> VTT files can contain font names/sizes and styles which should be used in the preview. ATM, mpv handles the VTT preview stuff, so the "video player settings" is not used.

[VTT File.zip](https://github.com/SubtitleEdit/subtitleedit/files/11592639/VTT.File.zip)

Had to send the file in zip because github doesn't support posting vtt files directly.

**Comment by GrampaWildWilly** [comment]
I think if you rename the file from whatever.vtt to whatever.txt, you can attach it here.  But zipping it is more polite.

Nik, the subtitle file posted by JustDevs does not appear to have any formatting directives, just the timing controls & the text of the subtitles.  The example I'm attaching is the same.  But I don't think the subtitles themselves or vtt vs assa is the issue.  The issue is that there is a setting in SE that the MPV player seems to be selectively honoring or ignoring.  There is also the issue that sometimes you lose image size.  Sometimes, fullscreen mode does not use the full screen because part of the space is occupied by a box in which the subtitles are displayed.  In one case, the subtitles go over top of the video image, like they should, allowing the image to occupy the full screen.  In the other case, there is this box that forces the fullscreen image to occupy less than the full screen, & the subtitles appear in the box.

<img width="960" alt="#01" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/621f2049-5b8b-4b31-9728-505814851e8d">
<img width="960" alt="#02" src="https://github.com/SubtitleEdit/subtitleedit/assets/75588964/e0b7acfd-21bd-4418-a5a0-6026b3ea18ab">
[La Traviata subtitles.zip](https://github.com/SubtitleEdit/subtitleedit/files/11594158/La.Traviata.subtitles.zip)

**Comment by GrampaWildWilly** [comment]
Sorry.  I tried about 5 different things before I managed to attach the zip file in my preceding post.  The images were no problem but the zip file was tricky.  I don't know why.  I did the same thing with the zip as with the images but it just wouldn't attach.  Whatever.  I've got it now.

**Comment by JustDevs** [comment]
@GrampaWildWilly The latest version changelog has this line:

* Allow raw WebVTT preview in mpv

I believe that issue is related to this change.

**Comment by GrampaWildWilly** [comment]
I hadn't noticed that but that sounds reasonable.  Is that entry in the changelog notifying us of the addition of that checkbox on the settings page in my most recent images?  Or is there a setting somewhere else that specifically mentions "raw" as opposed to formatted vtt subtitles?  I've just swept through all my SE settings & I don't see a different setting that seems related to this issue.  Was there some change in the way MPV displayed WEBVTT subtitles?  I don't remember.  Seems to me MPV used to display vtt subtitles the way I wanted but I wasn't particularly focused on that so I can't say for certain.  And I really don't feel like downloading & reinstalling a backlevel version of SE to check.  Normally, I have a couple of older zip files of SE hanging around here, but I was several versions out of date when I installed 3.6.13 beta 8 so I deleted all the old zips I had.

In any case, I think we both want to see formatted subtitles being displayed in MPV, which includes honoring the font specification on that panel of settings, independent of whether that checkbox is checked.  Raw should be a separate setting.  Raw should be for special cases in which somebody is particularly interested in the raw vtt.  Normally, I just want to see the formatted subtitles.  And I don't really care whether the code formatting the subtitles is in MPV.  Whoever displays the subtitles should honor the font specification.  And that ugly box has got to go.

**Comment by JustDevs** [comment]
@GrampaWildWilly That checkbox was also in the older version as far as I'm aware.

**Comment by GrampaWildWilly** [comment]
I hadn't noticed that but that sounds reasonable.  Is that entry in the changelog notifying us of the addition of that checkbox on the settings page in my most recent images?  Or is there a setting somewhere else that specifically mentions "raw" as opposed to formatted vtt subtitles?  I've just swept through all my SE settings & I don't see a different setting that seems related to this issue.  Was there some change in the way MPV displayed WEBVTT subtitles?  I don't remember.  Seems to me MPV used to display vtt subtitles the way I wanted but I wasn't particularly focused on that so I can't say for certain.  And I really don't feel like downloading & reinstalling a backlevel version of SE to check.  Normally, I have a couple of older zip files of SE hanging around here, but I was several versions out of date when I installed 3.6.13 beta 8 so I deleted all the old zips I had.

In any case, I think we both want to see formatted subtitles being displayed in MPV, which includes honoring the font specification on that panel of settings, independent of whether that checkbox is checked.  Raw should be a separate setting.  Raw should be for special cases in which somebody is particularly interested in the raw vtt.  Normally, I just want to see the formatted subtitles.  And I don't really care whether the code for formatting the subtitles is in MPV.  Whoever displays the subtitles should honor the font specification.  And that ugly outline box around the subtitles has got to go.

I lied.  I'm running SE in portable mode.  I think.  So I actually don't have to uninstall my current SE to install a backlevel version.  Because I'm not actually installing any version of SE.  So I got SE 3.6.12 out of the GIT archive.  The checkbox on that settings panel is there in 3.6.12 but the settings you see with & without the box checked are different between 3.6.12 & 3.6.13 beta 8.  Moreover, MPV in SE 3.6.12 displays the subtitles obeying my font selection with & without the settings box checked.  So there's some sort of regression between 3.6.12 & 3.6.13 beta 8.

I have also noticed that when I check & uncheck that box, I need to close & reopen SE.  Otherwise, the outline box for the subtitles seems to persist.  Cycling SE makes the box around the subtitles go away when it should.  However, the outline box is there in 3.6.12, same as 3.6.13 beta 8.  So I don't know when that started.  Maybe it's always been like that but I've always had the settings box checked so I never noticed.  In any case, the box around the subtitles should not appear when you're in fullscreen mode, independent of the settings box for letting MPV handle the subtitles.

**Comment by GrampaWildWilly** [comment]
To make it clear, there are 2 issues going on here:

1. MPV does not always honor the font selection now & it used to.
2. There is an outline box around the subtitles in fullscreen mode & there should not be.  This outline box reduces fullscreen MPV to not occupy the full screen.

**Comment by JustDevs** [comment]
@niksedk Can we have a quick patch that fixes this issue?

**Comment by GrampaWildWilly** [comment]
Just looking to have this issue get a little love.

**Comment by GrampaWildWilly** [comment]
I was beginning to wonder if this thread had gone invisible.  But I see I have collected a couple of thumbs on my last post so at least some people are seeing it.  Now if we could just get Nik to see it.  That would be, to see it again.  He saw it earlier.  He's usually more responsive than this.  Even if it's just to say it's on his to do list but not particularly near the top, that would be acceptable.  As long as I know he's accepted this as something to look into, I'll let it lie for now.

**Comment by niksedk** [comment]
Yes, "WebVTT raw preview in mpv" is a new feature, that let mpv handle the WebVTT format raw/directly.
You can turn back the old behavior by clearing the tag `MpvAllowNativePreview` in Settings.xml file.

The do believe the best fix is making a `WebVTT to ASSA converter`...

**Comment by GrampaWildWilly** [comment]
OK.  I changed the line to this:

<MpvAllowNativePreview></MpvAllowNativePreview>

I hope that's what you meant, as opposed to completely removing the line.  This does appear to make MPV honor the font selection independent of the checkbox for having MPV handle the preview.  But with the checkbox unchecked, the subtitles still go in a big grey box at the bottom, thus defeating the fullscreen effect.  I don't think that has anything to do with ASSA.  Besides, all of my subtitle files are vtt.  I'm not going to convert them.

Disabling the setting in the XML file makes MPV honor the font selection, with or without the checkbox.  That's one problem at least circumvented if not solved.

There is still the issue of the grey box.  That has nothing to do with fonts.  That's another bug.  Do you want me to open another thread for that?

**Comment by GrampaWildWilly** [comment]
Oops.  Sorry.  I had to edit that to make the XML tag appear in my post.

**Comment by niksedk** [comment]
OK, I will look into the grey box... screenshot?

The WebVTT to ASSA would just be internal.
mpv is very good at displaying ASSA, but not good at displaying WebVTT. 
I will try to make the preview auto-convert WebVTT to ASSA... it might work ;)

**Comment by GrampaWildWilly** [comment]
Thanks, Nik.  You always come through.

Screenshot is above, in the second post in this thread, along with complete explanation.

**Comment by GrampaWildWilly** [comment]
Thinking more on this . . .

Are you going to convert each subtitle one at a time on the fly from vtt to assa?  Including if we skip back or forward?  Including if we change a subtitle?  Is that a lot of code?  Will that cause a noticeable performance penalty?

When you do come out with something, I'll want to know a few things.

Do I keep Settings.Xml with `<MpvAllowNativePreview></MpvAllowNativePreview>`?  Actually, it has changed to `<MpvAllowNativePreview />`.

Do I reinstate `<MpvAllowNativePreview>WebVTT;WebVTT File with#</MpvAllowNativePreview>`?

Will SE just change that line to something else?

Will SE simply remove that line?

Some other possibility I don't have the imagination to ask about?

Do be sure to say, not now, when you tell us to go try a new beta.

**Comment by GrampaWildWilly** [comment]
Here's a section of my file:

`
    <MpvVideoOutputWindows />
    <MpvVideoOutputLinux>x11</MpvVideoOutputLinux>
    <MpvVideoVf />
    <MpvVideoAf />
    <MpvExtraOptions />
    <MpvAllowNativePreview />
    <MpvLogging>False</MpvLogging>
    <MpvHandlesPreviewText>True</MpvHandlesPreviewText>
    <MpvPreviewTextPrimaryColor>White</MpvPreviewTextPrimaryColor>
    <MpvPreviewTextOutlineColor>#ff000000</MpvPreviewTextOutlineColor>
    <MpvPreviewTextBackgroundColor>#ff000000</MpvPreviewTextBackgroundColor>
    <MpvPreviewTextOutlineWidth>1</MpvPreviewTextOutlineWidth>
    <MpvPreviewTextShadowWidth>1</MpvPreviewTextShadowWidth>
    <MpvPreviewTextOpaqueBox>False</MpvPreviewTextOpaqueBox>
    <MpvPreviewTextOpaqueBoxStyle>1</MpvPreviewTextOpaqueBoxStyle>
    <MpvPreviewTextAlignment>2</MpvPreviewTextAlignment>
    <MpvPreviewTextMarginVertical>10</MpvPreviewTextMarginVertical>
`

The 6th line of that is what I have now.  Before I did what Nik said to do, that line looked like this:

`<MpvAllowNativePreview>WebVTT;WebVTT File with#</MpvAllowNativePreview>`

I hope this helps.

**Comment by GrampaWildWilly** [comment]
Eww.  The Crl+e code thing loses all the line breaks.  What a mess.  It looks better in the E-mail you'll get, assuming you're subscribed to the thread.

**Comment by GrampaWildWilly** [comment]
Let's see how this looks.  I've changed all the angle brackets to square brackets.  But that's just to make it display nice here.  The real file has angle brackets, like what you see in HTML or XML.

    [MpvVideoOutputWindows /]
    [MpvVideoOutputLinux]x11[/MpvVideoOutputLinux]
    [MpvVideoVf /]
    [MpvVideoAf /]
    [MpvExtraOptions /]
    [MpvAllowNativePreview /]
    [MpvLogging]False[/MpvLogging]
    [MpvHandlesPreviewText]True[/MpvHandlesPreviewText]
    [MpvPreviewTextPrimaryColor]White[/MpvPreviewTextPrimaryColor]
    [MpvPreviewTextOutlineColor]#ff000000[/MpvPreviewTextOutlineColor]
    [MpvPreviewTextBackgroundColor]#ff000000[/MpvPreviewTextBackgroundColor]
    [MpvPreviewTextOutlineWidth]1[/MpvPreviewTextOutlineWidth]
    [MpvPreviewTextShadowWidth]1[/MpvPreviewTextShadowWidth]
    [MpvPreviewTextOpaqueBox]False[/MpvPreviewTextOpaqueBox]
    [MpvPreviewTextOpaqueBoxStyle]1[/MpvPreviewTextOpaqueBoxStyle]
    [MpvPreviewTextAlignment]2[/MpvPreviewTextAlignment]
    [MpvPreviewTextMarginVertical]10[/MpvPreviewTextMarginVertical]

**Comment by GrampaWildWilly** [comment]
Or . . . Change all the less than signs to |ampersand|lt; & all the greater than signs to |ampersand|gt;.  That's how HTML works.  Let's see how this looks:

`    &lt;MpvVideoOutputWindows /&gt;
    &lt;MpvVideoOutputLinux&gt;x11&lt;/MpvVideoOutputLinux&gt;
    &lt;MpvVideoVf /&gt;
    &lt;MpvVideoAf /&gt;
    &lt;MpvExtraOptions /&gt;
    &lt;MpvAllowNativePreview /&gt;
    &lt;MpvLogging&gt;False&lt;/MpvLogging&gt;
    &lt;MpvHandlesPreviewText&gt;True&lt;/MpvHandlesPreviewText&gt;
    &lt;MpvPreviewTextPrimaryColor&gt;White&lt;/MpvPreviewTextPrimaryColor&gt;
    &lt;MpvPreviewTextOutlineColor&gt;#ff000000&lt;/MpvPreviewTextOutlineColor&gt;
    &lt;MpvPreviewTextBackgroundColor&gt;#ff000000&lt;/MpvPreviewTextBackgroundColor&gt;
    &lt;MpvPreviewTextOutlineWidth&gt;1&lt;/MpvPreviewTextOutlineWidth&gt;
    &lt;MpvPreviewTextShadowWidth&gt;1&lt;/MpvPreviewTextShadowWidth&gt;
    &lt;MpvPreviewTextOpaqueBox&gt;False&lt;/MpvPreviewTextOpaqueBox&gt;
    &lt;MpvPreviewTextOpaqueBoxStyle&gt;1&lt;/MpvPreviewTextOpaqueBoxStyle&gt;
    &lt;MpvPreviewTextAlignment&gt;2&lt;/MpvPreviewTextAlignment&gt;
    &lt;MpvPreviewTextMarginVertical&gt;10&lt;/MpvPreviewTextMarginVertical&gt;`

**Comment by GrampaWildWilly** [comment]
Nope.  How about this?

    &lt;MpvVideoOutputWindows /&gt;
    &lt;MpvVideoOutputLinux&gt;x11&lt;/MpvVideoOutputLinux&gt;
    &lt;MpvVideoVf /&gt;
    &lt;MpvVideoAf /&gt;
    &lt;MpvExtraOptions /&gt;
    &lt;MpvAllowNativePreview /&gt;
    &lt;MpvLogging&gt;False&lt;/MpvLogging&gt;
    &lt;MpvHandlesPreviewText&gt;True&lt;/MpvHandlesPreviewText&gt;
    &lt;MpvPreviewTextPrimaryColor&gt;White&lt;/MpvPreviewTextPrimaryColor&gt;
    &lt;MpvPreviewTextOutlineColor&gt;#ff000000&lt;/MpvPreviewTextOutlineColor&gt;
    &lt;MpvPreviewTextBackgroundColor&gt;#ff000000&lt;/MpvPreviewTextBackgroundColor&gt;
    &lt;MpvPreviewTextOutlineWidth&gt;1&lt;/MpvPreviewTextOutlineWidth&gt;
    &lt;MpvPreviewTextShadowWidth&gt;1&lt;/MpvPreviewTextShadowWidth&gt;
    &lt;MpvPreviewTextOpaqueBox&gt;False&lt;/MpvPreviewTextOpaqueBox&gt;
    &lt;MpvPreviewTextOpaqueBoxStyle&gt;1&lt;/MpvPreviewTextOpaqueBoxStyle&gt;
    &lt;MpvPreviewTextAlignment&gt;2&lt;/MpvPreviewTextAlignment&gt;
    &lt;MpvPreviewTextMarginVertical&gt;10&lt;/MpvPreviewTextMarginVertical&gt;

**Comment by JustDevs** [comment]
@GrampaWildWilly What version are you using? 3.6.13 or Beta one?

**Comment by GrampaWildWilly** [comment]
3.6.13 beta 35

**Comment by JustDevs** [comment]
Oh ok, I had the release version, thanks.

**Comment by GrampaWildWilly** [comment]
I give up on the formatting thing.  I could just attach the file but that's not the point.  I want to post text that shows the less than & greater than signs as those characters.  I don't want the site here to interpret them as HTML.  I'm not finding the magic formula for doing that.  Maybe there's an escape character but I don't know what it is.

**Comment by GrampaWildWilly** [comment]
I've always assumed that if you're not using the latest beta, you shouldn't even post here.  Nik puts out betas for a reason.  Don't make him waste his time diagnosing problems he's already solved.  Always get the latest beta.  That's the rule I've always applied to myself.  I thought it was just understood around here.
/

**Comment by GrampaWildWilly** [comment]
Maybe the slash commands will do the trick.  I'll try Code Block.

```html
    <MpvVideoOutputWindows />
    <MpvVideoOutputLinux>x11</MpvVideoOutputLinux>
    <MpvVideoVf />
    <MpvVideoAf />
    <MpvExtraOptions />
    <MpvAllowNativePreview />
    <MpvLogging>False</MpvLogging>
    <MpvHandlesPreviewText>True</MpvHandlesPreviewText>
    <MpvPreviewTextPrimaryColor>White</MpvPreviewTextPrimaryColor>
    <MpvPreviewTextOutlineColor>#ff000000</MpvPreviewTextOutlineColor>
    <MpvPreviewTextBackgroundColor>#ff000000</MpvPreviewTextBackgroundColor>
    <MpvPreviewTextOutlineWidth>1</MpvPreviewTextOutlineWidth>
    <MpvPreviewTextShadowWidth>1</MpvPreviewTextShadowWidth>
    <MpvPreviewTextOpaqueBox>False</MpvPreviewTextOpaqueBox>
    <MpvPreviewTextOpaqueBoxStyle>1</MpvPreviewTextOpaqueBoxStyle>
    <MpvPreviewTextAlignment>2</MpvPreviewTextAlignment>
    <MpvPreviewTextMarginVertical>10</MpvPreviewTextMarginVertical>
```

**Comment by GrampaWildWilly** [comment]
Yay!  Learn something every day . . .

**Comment by JustDevs** [comment]
> I've always assumed that if you're not using the latest beta, you shouldn't even post here. Nik puts out betas for a reason. Don't make him waste his time diagnosing problems he's already solved. Always get the latest beta. That's the rule I've always applied to myself. I thought it was just understood around here. /

I'm new to this software and the community so how would I know? Anyways, the problem is solved now. Thanks for the help. Should I close this issue?

**Comment by GrampaWildWilly** [comment]
Not yet.  Nik is looking into that gray box thing I was talking about.

**Comment by niksedk** [comment]
I'm working a bit on WebVTT atm.
Hopefully the preview will be better and the styling via the `c` tag will be more "native" to SE. But it will take some time.
A very early version is here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by GrampaWildWilly** [comment]
A quick test of SE 3.6.13 beta 46 shows that the font specification is honored both when the checkbox is checked & when it is not checked for MPV to handle preview.  That one looks like a winner.

This may not be relevant but I did notice a change dealing with the gray box under the video aperture.  When MPV is NOT handling the preview, the subtitles still don't appear within the video aperture.  Fullscreen MPV is still not actually occupying the full screen.  But the video aperture is now surrounded on all 4 sides by blackness.  So the subtitles appear on a black background instead of on the gray box you can see in the image I posted way way way upthread.  So I suppose that's progress.  The gray box was really ugly.  Just plain black all around the video seems, to my eye anyway, a little less ugly than that gray box.  So I'm encouraged you're working on MPV & I look forward to whatever you come up with next.

**Comment by GrampaWildWilly** [comment]
I'm up to 3.6.13 beta 268 now.  I was wondering about the manual change to Settings.xml we did a fair piece upthread here.  I started with a line that read

```
<MpvAllowNativePreview>WebVTT;WebVTT File with#</MpvAllowNativePreview>
```

I changed it by hand to this:

```
<MpvAllowNativePreview />
```

Looking in the Settings.xml for this latest SE, this XML tag seems to have disappeared.  I'm guessing you deimplemented this particular tag & I can simply throw away the old line I have been preserving from when I did this.

In addition, whatever else you did seems to have cured the last of the issues I was talking about.  The captions now appear over the video aperture of the MPV player window & fullscreen actually occupies the full screen.  No more grey or black boxes.

Well, there is one black box but I think it's actually OK.  Seems to me in the past, captions just appeared on top of the video aperture without any sort of outline.  Now, there is a form-fitting black box around the captions.  This is rather tidy & helpful.  When the bottom portion of the video happens to be white, the white text of the captions could go invisible.  Except now, the form-fitting black box will ensure that never happens.  I call that a large step forward.

I think this one can be closed as fixed.  But I'm not sure if you, Nik, have any further work you were meaning to do here so I'll leave it to you to make the decision whether to close this.

**Comment by niksedk** [comment]
I presume this is working in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.13/SubtitleEditBeta.zip

**Comment by GrampaWildWilly** [comment]
It was working when I last posted a month ago.  I assume you haven't touched any part of whatever you did here while making updates to other parts of SE.  I would still like to know about the line in Settings.XML that used to be there & now isn't.  See my post upthread dated July 18 for details.

**Comment by niksedk** [comment]
WebVTT styling is now re-written in SE - has a style manager like ASSA, but it only supports the most common stuff.

**Comment by GrampaWildWilly** [comment]
I am revisiting this antique, not really reopening it, because of something I discovered about VTT font handling.  I am up to 4.0.6 beta 34 now, a year later.  In the `Settings` dialog on the `Video player` page I am telling MPV to handle preview text.  In the settings lower on that page, I have selected the radio button for `Opaque box` but I wasn't actually seeing the opaque box, which appears to have been something I was seeing a year ago, according to some of my comments above.  But I figured out how to make it appear.  I believe the settings for accomplishing this did not exist a year ago.  The `Settings` dialog itself has changed a lot since then as well.  It used to have tabs across the top but now the sections are in a list down the left side, which I think is an improvement.

Anyway.  The opaque box.  When you select that radio button, a drop-down list with 2 entries appears.  I have selected `One box (use shadow color)`.  That contains a clue pointing you to what you need to do.  You need to click the button just to the left of that labelled `Shadow`.  Clicking that button opens a color selector dialog.  I want a black box so I slid all three of the RGB sliders to 0.  But I wasn't getting the black box around the subtitles.  I also had to slide the Alpha slider all the way up to 255.  Then it started working.

All the other blather above about the gray box around the MPV display aperture has been solved, although actually making MPV go fullscreen is a bit of a nuisance, as I've been pursuing in #8358.  So this one can stay closed.  I just wanted to leave a note for anyone who might stumble across this discussion.
