### ISSUE TITLE
Audio to text window disappears when clicking the minimize button and cannot be brought forward

### ISSUE THREAD

**Issue by mzso** [SubtitleEdit/subtitleedit#9084]
Also the main window remains in place so it's a double issue. The app can't be minimized when audio to text is running.

The process takes a long time so one would prefer to hide the window for the time but be able to bring up the audio to text window if needed.

The only non-traditional way I found to get the window back was using the Process Explorer program, and its bring to front feature for the window.

PS:
Also a worthy enhancement would be to save subtitles while the process is running, it takes an awful lot of time but it's slightly faster than real-time.

**Comment by niksedk** [comment]
Minimize/re-active should be fixed in latest beta :)

**Comment by mzso** [comment]
Thanks!
Using this feature a bit I have some other suggestions. It would be nice if the cancel button wouldn't be pre-selected, it's easy to hit accidentally when I alt+tab away and back. (especially without the ability to minimize) Even better would be a pause/resume button if possible, and definitely a confirmation prompt to cancel, since it takes an excruciatingly long time to finish for longer audio.
(Not really important, but the beep when converting multiple items might be annoying to some.)

**Comment by niksedk** [comment]
The "Generate" button is focused here...

**Comment by mzso** [comment]
[**@niksedk**](https://github.com/niksedk) commented on [Dec 29, 2024, 4:40 PM GMT+1](https://github.com/SubtitleEdit/subtitleedit/issues/9084#issuecomment-2564762284 "2024-12-29T15:40:39Z - Replied by Github Reply Comments"):
> The "Generate" button is focused here...
> 
> Pause is not really possible, sorry.
> 
> _Originally posted by @niksedk in https://github.com/SubtitleEdit/subtitleedit/issues/9084#issuecomment-2564762284_

I meant after starting the generation process. Focus jumpst to "cancel".

I can't really test the minimize button, because the engine I used (Purfview-Whisper-Faster) disappeared, and the default given (CPP) fails to do anything, and just ends immediately with producing an empty srt file.

**Comment by mzso** [comment]
@niksedk Okay. So I tried with Faster-Whisper-XXL. And the original issue is still half present. The main window is now minimized, but I still only can restore the "Audio to Text" window via process explorer.

And another issue seems to have come up. The progress bar is not working anymore. When the state is "Transcribing audio to text the progress bar starts with full and remains like that until it finishes.
