### ISSUE TITLE
Constant parse errors when using DeepL / DeeplX Translate APIs

### ISSUE THREAD

**Issue by Hypn0iid** [SubtitleEdit/subtitleedit#9305]
Parse error: unknown token.
   em Nikse.SubtitleEdit.Core.Common.JsonParser.Literal()
   em Nikse.SubtitleEdit.Core.Common.JsonParser.Parse(String text)
   em Nikse.SubtitleEdit.Core.AutoTranslate.DeepLTranslate.Translate(String text, String sourceLanguageCode, String targetLanguageCode, CancellationToken cancellationToken)
   em Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()

**Comment by niksedk** [comment]
Do the file `error_log.txt` say anything about this?

**Comment by Hypn0iid** [comment]
> Do the file `error_log.txt` say anything about this?

Date: 02/02/2025 11:39:11
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit
Message: DeepLTranslate error: <html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>


-----------------------------------------------------------------------------
Date: 02/02/2025 11:39:11
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit

Nikse.SubtitleEdit.Core.Common.ParserException
Message: Parse error: unknown token.
StackTrace:    em Nikse.SubtitleEdit.Core.Common.JsonParser.Literal()
   em Nikse.SubtitleEdit.Core.Common.JsonParser.Parse(String text)
   em Nikse.SubtitleEdit.Core.AutoTranslate.DeepLTranslate.Translate(String text, String sourceLanguageCode, String targetLanguageCode, CancellationToken cancellationToken)
   em Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
-----------------------------------------------------------------------------
Date: 02/02/2025 11:39:44
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit
Message: DeepLTranslate error: <html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>


-----------------------------------------------------------------------------
Date: 02/02/2025 11:39:44
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit

Nikse.SubtitleEdit.Core.Common.ParserException
Message: Parse error: unknown token.
StackTrace:    em Nikse.SubtitleEdit.Core.Common.JsonParser.Literal()
   em Nikse.SubtitleEdit.Core.Common.JsonParser.Parse(String text)
   em Nikse.SubtitleEdit.Core.AutoTranslate.DeepLTranslate.Translate(String text, String sourceLanguageCode, String targetLanguageCode, CancellationToken cancellationToken)
   em Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
-----------------------------------------------------------------------------
Date: 02/02/2025 11:39:53
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit
Message: DeepLTranslate error: <html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>


-----------------------------------------------------------------------------
Date: 02/02/2025 11:39:53
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit

Nikse.SubtitleEdit.Core.Common.ParserException
Message: Parse error: unknown token.
StackTrace:    em Nikse.SubtitleEdit.Core.Common.JsonParser.Literal()
   em Nikse.SubtitleEdit.Core.Common.JsonParser.Parse(String text)
   em Nikse.SubtitleEdit.Core.AutoTranslate.DeepLTranslate.Translate(String text, String sourceLanguageCode, String targetLanguageCode, CancellationToken cancellationToken)
   em Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
-----------------------------------------------------------------------------
Date: 02/02/2025 11:39:57
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit
Message: DeepLTranslate error: <html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>


-----------------------------------------------------------------------------
Date: 02/02/2025 11:39:57
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit

Nikse.SubtitleEdit.Core.Common.ParserException
Message: Parse error: unknown token.
StackTrace:    em Nikse.SubtitleEdit.Core.Common.JsonParser.Literal()
   em Nikse.SubtitleEdit.Core.Common.JsonParser.Parse(String text)
   em Nikse.SubtitleEdit.Core.AutoTranslate.DeepLTranslate.Translate(String text, String sourceLanguageCode, String targetLanguageCode, CancellationToken cancellationToken)
   em Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()
-----------------------------------------------------------------------------
Date: 02/02/2025 11:40:14
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit
Message: DeepLTranslate error: <html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>


-----------------------------------------------------------------------------
Date: 02/02/2025 11:40:14
SE: 4.0.11.0 - Microsoft Windows NT 10.0.26100.0 - 64-bit

Nikse.SubtitleEdit.Core.Common.ParserException
Message: Parse error: unknown token.
StackTrace:    em Nikse.SubtitleEdit.Core.Common.JsonParser.Literal()
   em Nikse.SubtitleEdit.Core.Common.JsonParser.Parse(String text)
   em Nikse.SubtitleEdit.Core.AutoTranslate.DeepLTranslate.Translate(String text, String sourceLanguageCode, String targetLanguageCode, CancellationToken cancellationToken)
   em Nikse.SubtitleEdit.Forms.Translate.AutoTranslate.<buttonTranslate_Click>d__33.MoveNext()

**Comment by niksedk** [comment]
Does this occur all the time... or just once in a while?

**Comment by Hypn0iid** [comment]
> Does this occur all the time... or just once in a while?

It didn't happen before, like a few months back. But now it happens all the time. I have to click "Ok" on the error and then translate again so it continues to translate the file, it's really annoying to do this every 10 seconds or so.

**Comment by niksedk** [comment]
Is latest beta any better? https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.11/SubtitleEditBeta.zip
Hopefully it will now do some retrying...

**Comment by Hypn0iid** [comment]
No, now the translation doesn't really work at all. It looks like it's doing something but It doens't fill the translated boxes and it continues to show an error, even though this time nothing shows in the error_log, only the popup:

![Image](https://github.com/user-attachments/assets/f65c5466-cb55-468e-a2ff-dff697815355)

**Comment by niksedk** [comment]
OK, retry should work now: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.11/SubtitleEditBeta.zip

**Comment by Hypn0iid** [comment]
Now there is no errors, but the translation isn't doing anything. It's running but it's not filling the text boxes.

![Image](https://github.com/user-attachments/assets/921df8bb-7b95-4fb7-9c4d-0758cbdadc80)

**Comment by niksedk** [comment]
Thx, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.11/SubtitleEditBeta.zip
(was a problem with the new languages)

**Comment by Hypn0iid** [comment]
> Thx, beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.11/SubtitleEditBeta.zip (was a problem with the new languages)

Perfect! There are no errors, and everything works regarding this issue.

**Comment by Hypn0iid** [comment]
sorry to write again on this issue, don't know if I should open a new one. But this problem still occurs if I choose Line merge: "Translate each line seperately" in the advanced options of DeepL @niksedk
